#! /usr/bin/env bash
#
#   Copyright (c) 2015 Nat! - Mulle kybernetiK
#   All rights reserved.
#
#   Redistribution and use in source and binary forms, with or without
#   modification, are permitted provided that the following conditions are met:
#
#   Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
#   Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
#   Neither the name of Mulle kybernetiK nor the names of its contributors
#   may be used to endorse or promote products derived from this software
#   without specific prior written permission.
#
#   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#   AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#   IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#   ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#   LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#   CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#   SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#   INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#   CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#   ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#   POSSIBILITY OF SUCH DAMAGE.
#
[ "${TRACE}" = "YES" ] && set -x && : "$0" "$@"

MULLE_ENV_VERSION="0.10.1"

#
# use mulle:restrict as the default suitable for first time mulle-sde
# users
#
MULLE_ENV_DEFAULT_STYLE="${MULLE_ENV_DEFAULT_STYLE:-mulle:restrict}"


usage()
{
    cat <<EOF >&2
Usage:
   ${MULLE_EXECUTABLE_NAME} [options] [commands] [path|url]

   Use a virtual environment for your project.
   If the directory at path does not exist and the path looks like an url,
   ${MULLE_EXECUTABLE_NAME} will attempt to git clone the project from that url.

   Styles are a toolstyle and a pathstyle, separated by ':'

Commands:
   environment          : manage environment variables
   init                 : set up the environment for the first time
   tool                 : manage tools
   uname                : return the ${MULLE_EXECUTABLE_NAME} specfic uname
   version              : return the ${MULLE_EXECUTABLE_NAME} version
   --                   : enter the environment. Can be left out if path, url are
                          not named like the other commands.
Options:
   --style <tool:path>  : enter environment with a certain flavor
   -c <cmd>             : shell command to execute instead of interactive shell
   -d <dir>             : specify directory
EOF
   options_technical_flags_usage "               : "

   cat <<EOF >&2

Tool-style:
   none                 : no additions
   mulle                : additionally support mulle-build (default)

Path-style:
   none                 : all tools must be specified in .mulle-env/etc/tools
   inherit              : inherit PATH, don't use tools links
   restrict             : /bin and /usr/bin are inherited. All other tools must
                          be specified.
   wild                 : inherit PATH and inherit environment
EOF


  exit 1
}


censored_path()
{
   log_entry "censored_path" "$@"

   local result

   local i
   local j

   IFS=":"
   for i in $*
   do
      IFS=":"
      for j in ${RESTRICTED_PATH}
      do
         IFS="${DEFAULT_IFS}"

         if [ "$i" = "$j" ]
         then
            result="`colon_concat "${result}" "${i}"`"
         fi
      done
   done

   IFS="${DEFAULT_IFS}"

   if [ ! -z "${result}" ]
   then
      echo "${result}"
   fi
}


env_link_other_tool()
{
   log_entry "env_link_other_tool" "$@"

   local toolname="$1"
   local bindir="$2"
   local isrequired="$3"

   local filename

   filename="`command -v "${toolname}" `"
   if [ -z "${filename}" ]
   then
      if [ "${isrequired}" = "YES" ]
      then
         fail "Required tool \"${toolname}\" not found"
      fi

      log_fluff "\"${toolname}\" not found, but it's optional"
      return 1
   fi

   log_fluff "Creating symlink \"${bindir}/${toolname}\""

   exekutor ln -sf "${filename}" "${bindir}"
}


env_link_other_tools()
{
   log_entry "env_link_other_tools" "$@"

   local toolnames="$1"
   local directory="$2"
   local isrequired="$3"

   local toolname

   local bindir

   bindir="${directory}/bin"

   mkdir_if_missing "${bindir}"

   IFS="
"
   for toolname in ${toolnames}
   do
      IFS="${DEFAULT_IFS}"

      if [ -z "${toolname}" ]
      then
         continue
      fi

      env_link_other_tool "${toolname}" "${bindir}" "${isrequired}"
   done

   IFS="${DEFAULT_IFS}"

   rmdir_if_empty "${bindir}"
}


env_other_tool_files()
{
   log_entry "env_other_tool_files" "$@"

   local directory="$1"

   [ -z "${directory}" ] && internal_fail "directory must not be empty"

   if [ ! -z "${HOME}" ]
   then
      echo "${HOME}/.config/mulle-env/tools"
      echo "${HOME}/.config/mulle-env/optional-tools"
   fi

   echo "${directory}/etc/tools"
   echo "${directory}/etc/optional-tools"
}


env_setup_other_tools()
{
   log_entry "env_setup_other_tools" "$@"

   local toolfiles="$1"
   local directory="$2"

   local tools
   local toolfile

   IFS="
"
   for toolfile in ${toolfiles}
   do
      IFS="${DEFAULT_IFS}"

      if tools="`cat "${toolfile}" `"
      then
         case "${toolfile}" in
            optional-*|*/optional-*)
               env_link_other_tools "${tools}" "${directory}" "NO"
            ;;

            *)
               env_link_other_tools "${tools}" "${directory}" "YES"
            ;;
         esac
      fi
   done
   IFS="${DEFAULT_IFS}"

   return 0
}


env_setup_if_needed()
{
   log_entry "env_setup_if_needed" "$@"

   local directory="$1"
   local flavor="$2"

   local needs_flavor_update
   local needs_bin_update
   local needs_bin_update2

   needs_flavor_update=
   needs_bin_update=

   local etcdir
   local sharedir
   local bindir
   local libexecdir
   local cachedir

   cachedir="${directory}/var/cache"
   etcdir="${directory}/etc"
   sharedir="${directory}/share"
   bindir="${directory}/bin"
   libexecdir="${directory}/libexecdir"

   local callback

   callback="env_${flavor}_tools_need_update"
   if [ "`type -t "${callback}"`" = "function" ]
   then
      if ${callback} "${directory}"
      then
         log_fluff "Flavor \"${flavor}\" needs update"
         needs_flavor_update="YES"
      else
         log_fluff "Flavor \"${flavor}\" is up-to-date"
      fi
   fi

   local toolfile
   local oldhost
   local uptodatefile
   local myhost

   uptodatefile="${cachedir}/tools-updated"

   oldhost="`cat "${uptodatefile}" 2> /dev/null`"
   myhost="`hostname -s`"

   if [ ! -z "${oldhost}" -a "${oldhost}" != "${myhost}" ]
   then
      log_fluff "Regenerating tools as the host has changed"

      exekutor chmod ug+w "${bindir}" 2> /dev/null
      remove_file_if_present "${uptodatefile}"
      exekutor chmod ug-w "${bindir}" 2> /dev/null
   fi

   IFS="
"
   for toolfile in `env_other_tool_files "${directory}"`
   do
      IFS="${DEFAULT_IFS}"

      if [ -f "${toolfile}.${UNAME}" ]
      then
         toolfile="${toolfile}.${UNAME}"
      fi

      if [ "${OPTION_MAGNUM_FORCE}" = "YES" -a -f "${toolfile}" ] || \
         [ "${toolfile}" -nt "${uptodatefile}" ]
      then
         log_fluff "Tools \"${toolfile}\" needs update"
         needs_bin_update="`add_line "${needs_bin_update}" "${toolfile}" `"
      fi
   done
   IFS="${DEFAULT_IFS}"

   if [ -z "${needs_bin_update}" -a -z "${needs_flavor_update}" ]
   then
      log_verbose "Nothing needs to be updated"
      return
   fi

   #
   # unprotect
   #
   exekutor chmod -R ug+w "${bindir}" 2> /dev/null
   exekutor chmod -R ug+w "${libexecdir}" 2> /dev/null

   local callback

   callback="env_setup_${flavor}_tools"
   if [ "`type -t "${callback}"`" = "function" ]
   then
      ${callback} "${directory}"
   fi

   if [ ! -z "${needs_bin_update}" ]
   then
      env_setup_other_tools "${needs_bin_update}" "${directory}"

      log_fluff "Writing \"${uptodatefile}\""

      mkdir_if_missing "${cachedir}"
      redirect_exekutor "${uptodatefile}" echo "${myhost}"
   fi

   #
   # protect from accidents
   #
   exekutor chmod -R ugo-w "${libexecdir}" 2> /dev/null
   exekutor chmod -R ugo-w "${bindir}" 2> /dev/null
}


__get_saved_style_flavor()
{
   log_entry "__get_saved_style_flavor" "$@"

   local directory="$1"

   style=""
   if [ -f "${directory}/style" ]
   then
      style="`sed -e '/^#/d' -e 's/--style //' "${directory}/style" `"
   fi
   if [ -z "${style}" ]
   then
      fail "No mulle-env environment found. \"$directory/style\" is missing"
   fi
   flavor="`cut -d: -f1 <<< "${style}"`"
}


__get_user_style_flavor()
{
   log_entry "__get_user_style_flavor" "$@"

   local option="$1"

   style="${option}"
   if [ "${style}" = "DEFAULT" ]
   then
      style="${MULLE_ENV_DEFAULT_STYLE}"
   fi
   flavor="`cut -d: -f1 <<< "${style}"`"
}


__load_flavor_plugin()
{
   log_entry "__load_flavor_plugin" "$@"

   local flavor="$1"

   . "${MULLE_ENV_LIBEXEC_DIR}/mulle-env-plugins.sh" || exit 1

   env_load_plugin "${flavor}"
}


find_best_environment()
{
   log_entry "find_best_environment" "$@"

   local start="$1"

   local directory
   local best

   best="${start}"
   directory="`absolutepath "${start}"`"  # paranoia
   while :
   do
      directory="`dirname -- "${directory}"`"

      # look for .mulle-env/*/environment.sh going up to root, if we
      # find one, we latch onto it
      if [ "${directory}" = "/" ]
      then
         echo "${best}"
         return
      fi

      # use globbing
      if [ -f "${directory}/".mulle-env/*/environment.sh ]
      then
         log_info "Found and using a superior mulle-env environment at \
${C_RESET_BOLD}${directory}/.mulle-env${C_INFO}.
Suppress this behaviour with:
   ${C_RESET_BOLD}mulle-env --no-search"
         best="${directory}"
      fi
   done
}


apply_style_to_directory()
{
   log_entry "apply_style_to_directory" "$@"

   local directory="$1"
   local sharedir="$2"
   local style="$3"
   local flavor="$4"

   local callback

   callback="env_${flavor}_enter_subshell"
   if [ "`type -t "${callback}"`" = "function" ]
   then
      ${callback} "${directory}" "${style}"
   fi

   # memorize new style
   redirect_exekutor "${sharedir}/style" echo "--style ${style}"
}


apply_flavor_to_runpath()
{
   log_entry "apply_flavor_to_runpath" "$@"

   local directory="$1"
   local flavor="$2"
   local runpath="$3"

   local callback

   callback="env_${flavor}_add_runpath"
   if [ "`type -t "${callback}"`" = "function" ]
   then
      ${callback} "${directory}" "${runpath}"
   else
      echo "${runpath}"
   fi
}


_setup_environment()
{
   log_entry "_setup_environment" "$@"

   local directory="$1"

   local physicaldir

   physicaldir="`physicalpath "${directory}" `"
   [ ! -d "${physicaldir}" ] && internal_fail "physicalpath failed"

   MULLE_VIRTUAL_ROOT="${physicaldir}"

   log_verbose "MULLE_VIRTUAL_ROOT set to \"${MULLE_VIRTUAL_ROOT}\""

   MULLE_ENV_DIR="${physicaldir}/.mulle-env"

   log_fluff "MULLE_ENV_DIR set to \"${MULLE_ENV_DIR}\""
}


_default_setup_environment()
{
   log_entry "_default_setup_environment" "$@"

   local directory="${1:-${PWD}}"

   if [ "${OPTION_SEARCH}" = "YES" ]
   then
      directory="`find_best_environment "${PWD}"`"
   fi

   [ ! -d "${directory}" ] && fail "${directory} does not exist (init it first)"

   _setup_environment "${directory}"
}


main()
{
   log_entry "main" "$@"

   local OPTION_DIRECTORY
   local OPTION_BOOTSTRAP="NO"
   local OPTION_SHELL_COMMAND
   local OPTION_KEEP_TMP="NO"
   local OPTION_MAGNUM_FORCE=
   local OPTION_STYLE="DEFAULT"
   local OPTION_SEARCH="DEFAULT"

   local MULLE_FLAG_EXEKUTOR_DRY_RUN
   local MULLE_FLAG_LOG_DEBUG
   local MULLE_FLAG_LOG_EXEKUTOR
   local MULLE_FLAG_LOG_TERSE
   local MULLE_TRACE

   local RESTRICTED_PATH

   # mingw needs different values here

   case "${MULLE_UNAME}" in
      "")
         internal_fail "MULLE_UNAME not set"
      ;;

      *)
         RESTRICTED_PATH="/usr/bin:/bin"
      ;;
   esac

   while [ $# -ne 0 ]
   do
      if options_technical_flags "$1"
      then
         shift
         continue
      fi

      case "$1" in
         -h|--help)
            usage
         ;;

         -c)
            [ $# -eq 1 ] && fail "missing argument to $1"
            shift

            OPTION_SHELL_COMMAND="$1"
         ;;

         -f|--force)
            OPTION_MAGNUM_FORCE="YES"
         ;;

         -d|--directory)
            [ $# -eq 1 ] && fail "Missing argument to $1"
            shift

            OPTION_DIRECTORY="$1"
         ;;

         --search)
            OPTION_SEARCH="YES"
         ;;

         -ns|--no-search)
            OPTION_SEARCH="NO"
         ;;

         --bootstrap)
            OPTION_BOOTSTRAP="YES"
         ;;

         -nb|--no-bootstrap)
            OPTION_BOOTSTRAP="NO"
         ;;

         --keep-tmp)
            OPTION_KEEP_TMP="YES"
         ;;

         --)
            break
         ;;

         # argument gitflags
         -*)
            fail "Unknown flag \"$1\""
         ;;

         *)
            break
         ;;
      esac

      shift
   done

   options_setup_trace "${MULLE_TRACE}"
   export MULLE_TRACE

   local arg
   local url

   # callerdirectory is where we are called from
   local callerdirectory
   # directory is where we are supposed to execute
   local directory
   # MULLE_VIRTUAL_ROOT is where the .mulle-env/share/environment.sh is
   local MULLE_VIRTUAL_ROOT

   callerdirectory="`pwd -P`"

   arg="$1"
   [ $# -ne 0 ] && shift

   case "${arg}" in
      --)
         arg="$1"
         [ $# -ne 0 ] && shift
      ;;

      uname)
         echo "${MULLE_UNAME}"
         return 0
      ;;

      init)
         # shellcheck source=src/mulle-env-init.sh
         . "${MULLE_ENV_LIBEXEC_DIR}/mulle-env-init.sh" || exit 1

         env_init_main "$@"
         return $?
      ;;

      environment)
         # shellcheck source=src/mulle-env-environment.sh
         . "${MULLE_ENV_LIBEXEC_DIR}/mulle-env-environment.sh" || exit 1

         _default_setup_environment "${PWD}"
         env_environment_main "$@"
         return $?
      ;;

      tool)
         # shellcheck source=src/mulle-env-tool.sh
         . "${MULLE_ENV_LIBEXEC_DIR}/mulle-env-tool.sh" || exit 1

         _default_setup_environment "${PWD}"
         env_tool_main "$@"
         return $?
      ;;
   esac

   #
   # lets do this for now
   #
   if [ ! -z "${MULLE_VIRTUAL_ROOT}" ]
   then
      fail "You are already in the virtual \
environment \"${MULLE_VIRTUAL_ROOT}\". Environments don't stack."
   fi

   if [ ! -z "${OPTION_DIRECTORY}" ]
   then
      directory="${OPTION_DIRECTORY}"
   else
      if [ -z "${arg}" ]
      then
         directory="${callerdirectory}"
         if [ "${OPTION_SEARCH}" = "DEFAULT" ]
         then
            OPTION_SEARCH="YES"
         fi

      else
         directory="$arg"
      fi
   fi

   if [ ! -d "${directory}" ]
   then
      local url

      case "${arg}" in
         *:*)
            url="${arg}"
         ;;
      esac

      if [ ! -z "${url}" ]
      then
         if [ -z "`command -v git`" ]
         then
            fail "git not installed, can't clone stuff for you"
         fi

         directory="`basename -- "${url}" .git`"
         log_verbose "Cloning from URL \"${arg}\" into \"${directory}\"..."
         git clone "${url}" "${directory}" || return 1
      fi
   fi

   _default_setup_environment "${directory}"

   local etcdir
   local sharedir

   etcdir="${MULLE_ENV_DIR}/etc"
   sharedir="${MULLE_ENV_DIR}/share"

   local style
   local flavor

   __get_saved_style_flavor "${sharedir}"
   __load_flavor_plugin "${flavor}"

   local run_shell_args
   local inherit_path
   local runpath
   local rundirectory

   case "${style}" in
      *:*)
      ;;

      *) # no : like none
         style="${style:none}"
      ;;
   esac


   local s

   s=""

   local env_flag

   env_flag="-i"

   case "${style}" in
      *:wild)
         inherit_path="${PATH}"
         env_flag=""   # do not suppress environment
      ;;

      *:inherit)
         inherit_path="${PATH}"
      ;;

      *:restrict)
         env_setup_if_needed "${MULLE_ENV_DIR}" "${flavor}"
         inherit_path="`censored_path "${PATH}"`"
         runpath="`colon_concat "${runpath}" "${MULLE_ENV_DIR}/bin" `"

         s="`concat "${s}" "MULLE_OLDPATH='${PATH}'"`"
      ;;

      *:none)
         inherit_path=""
         env_setup_if_needed "${MULLE_ENV_DIR}" "${flavor}"
         runpath="`colon_concat "${runpath}" "${MULLE_ENV_DIR}/bin" `"

         s="`concat "${s}" "MULLE_OLDPATH='${PATH}'"`"
      ;;

      *)
         fail "unknown style \"${style}\""
      ;;
   esac


   runpath="`colon_concat "${runpath}" "${inherit_path}" `"
   runpath="`apply_flavor_to_runpath "${MULLE_VIRTUAL_ROOT}" "${flavor}" "${runpath}" `"

   log_debug "future PATH=${runpath}"

   rundirectory="${MULLE_VIRTUAL_ROOT}"
   if [ "${OPTION_SEARCH}" = "YES" ]
   then
      rundirectory="${callerdirectory}"
   fi
   apply_style_to_directory "${rundirectory}" "${sharedir}" "${style}" "${flavor}"

   #
   #
   #
   log_fluff "Run shell in \"${rundirectory}\"..."

   if [ ! -z "${OPTION_SHELL_COMMAND}" ]
   then
      run_shell_args="-c '${OPTION_SHELL_COMMAND}"
   fi

   case "${style}" in
      *:wild)
         unset MULLE_EXECUTABLE_NAME
      ;;

      *)
         [ ! -z "${DISPLAY}" ]   && s="`concat "${s}" "DISPLAY='${DISPLAY}'"`"
         [ ! -z "${EDITOR}" ]    && s="`concat "${s}" "EDITOR='${EDITOR}'"`"
         [ ! -z "${HOME}" ]      && s="`concat "${s}" "HOME='${HOME}'"`"
         [ ! -z "${LOGNAME}" ]   && s="`concat "${s}" "LOGNAME='${LOGNAME}'"`"
         [ ! -z "${LS_COLORS}" ] && s="`concat "${s}" "LS_COLORS='${LS_COLORS}'"`"
         [ ! -z "${PS1}" ]       && s="`concat "${s}" "PS1='${PS1}'"`"
         [ ! -z "${SSH_CONNECTION}" ] \
                                 && s="`concat "${s}" "SSH_CONNECTION='${SSH_CONNECTION}'"`"
         [ ! -z "${SSH_TTY}" ]   && s="`concat "${s}" "SSH_TTY='${SSH_TTY}'"`"
         [ ! -z "${TERM}" ]      && s="`concat "${s}" "TERM='${TERM}'"`"
         [ ! -z "${TMPDIR}" ]    && s="`concat "${s}" "TMPDIR='${TMPDIR}'"`"
         [ ! -z "${USER}" ]      && s="`concat "${s}" "USER='${USER}'"`"
         [ ! -z "${VISUAL}" ]    && s="`concat "${s}" "VISUAL='${VISUAL}'"`"
         [ ! -z "${DBUS_SESSION_BUS_ADDRESS}" ] \
                                 && s="`concat "${s}" "DBUS_SESSION_BUS_ADDRESS='${DBUS_SESSION_BUS_ADDRESS}'"`"
      ;;
   esac

   #
   # home is needed for git
   # otherwise provide a minimal environment, for better reproducability
   #
   cd "${rundirectory}" &&
   eval env ${env_flag} \
          "${s}" \
          "'${MULLE_ENV_LIBEXEC_DIR}/mulle-env-shell'" \
            "'${MULLE_UNAME}'" \
            "'${MULLE_VIRTUAL_ROOT}'" \
            "'${runpath}'" \
            "INTERACTIVE" \
            "${TRACE}" \
            "${run_shell_args}"
   return $?
}



########
###
### INIT
###
_init()
{
   if [ "$1" = "version" ]
   then
      echo "${MULLE_ENV_VERSION}"
      exit 0
   fi

   MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env libexec-dir 2> /dev/null`"
   [ -z "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" ] && \
      echo "mulle-bashfunctions-env not installed" >&2 && \
      exit 1

   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" "minimal" || exit 1
   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-path.sh" || exit 1
   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-file.sh" || exit 1

   local _libexec_dir

   _get_libexec_dir "$0" "mulle-env" "mulle-env-shell"

   if [ -z "${_libexec_dir}" ]
   then
      fail "Fatal Error: Could not find libexec for ${MULLE_EXECUTABLE} ($PWD)"
   fi
   MULLE_ENV_LIBEXEC_DIR="${_libexec_dir}"

   #
   # minimal setup exit
   #
   if [ "$1" = "libexec-dir" ]
   then
      echo "${MULLE_ENV_LIBEXEC_DIR}"
      exit 0
   fi

   set -o pipefail
}


_init "$@"
main "$@"

