#! /usr/bin/env bash

[ "${TRACE}" = 'YES' ] && set -x


run_mulle_env()
{
   log_fluff "####################################"
   log_fluff ${MULLE_ENV} ${MULLE_ENV_FLAGS} "$@"
   log_fluff "####################################"

   exekutor ${MULLE_ENV} ${MULLE_ENV_FLAGS} "$@"
}


main()
{
   MULLE_ENV_FLAGS="$@"

   _options_mini_main "$@"

   local directory

   directory="`make_tmp_directory`" || exit 1
   directory="${directory:-/tmp/exekutor}"

   cd "${directory}" || exit 1

   run_mulle_env -s init --style none/tight

   value="`run_mulle_env -s tool list | egrep '^mudo$'`"
   [ "${value}" != 'mudo' ] && fail "not mudois wrong here"

   if run_mulle_env tool add mudo
   then
      fail "Unexpected success of mudo add (should be 2)"
   fi

   log_verbose "----- #1 PASSED -----"

   value="`run_mulle_env -s tool list | egrep awk`"
   [ ! -z "${value}" ] && fail "awk is wrong here"

   if ! run_mulle_env tool add awk
   then
      fail "Unexpected add failure"
   fi

   value="`run_mulle_env -s tool list | egrep awk`"
   [ "${value}" != "awk" ] && fail "Not awk is wrong here"

   log_verbose "----- #2 PASSED -----"

   log_info "----- ALL PASSED -----"

   rmdir_safer "${directory}"
}



init()
{
   MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env libexec-dir`" || exit 1

   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1

   MULLE_ENV="${MULLE_ENV:-${PWD}/../../mulle-env}"
}



init "$@"
main "$@"

