#! /usr/bin/env bash

[ "${TRACE}" = 'YES' ] && set -x


run_mulle_env()
{
   log_fluff "####################################"
   log_fluff ${MULLE_ENV} ${MULLE_ENV_FLAGS} "$@"
   log_fluff "####################################"

   exekutor ${MULLE_ENV} ${MULLE_ENV_FLAGS} "$@"
}


main()
{
   MULLE_ENV_FLAGS="$@"

   _options_mini_main "$@"

   local directory

   directory="`make_tmp_directory`" || exit 1
   directory="${directory:-/tmp/exekutor}"

   cd "${directory}" || exit 1

   run_mulle_env -s init --style none/tight

   local value

   if run_mulle_env -f environment --scope s:DEFAULT set FOO 1
   then
      fail "Succeeded unexpectedly"
   fi
   if run_mulle_env -f environment --scope include set FOO 1
   then
      fail "Succeeded unexpectedly"
   fi
   if run_mulle_env -f environment --scope merged set FOO 1
   then
      fail "Succeeded unexpectedly"
   fi

   log_verbose "----- #1 PASSED -----"

   if ! run_mulle_env -f environment --scope plugin-foo set FOO 1
   then
      fail "Failed unexpectedly"
   fi

   [ ! -f .mulle/share/env/auxscope ] && fail ".mulle/share/env/auxscope should exist"
   [ -f  .mulle/etc/env/auxscope ]    && fail ".mulle/etc/env/auxscope should not exist"

   if ! run_mulle_env -f environment --scope user-foo set FOO 2
   then
      fail "Failed unexpectedly"
   fi

   [ ! -f .mulle/etc/env/auxscope ] && fail ".mulle/etc/env/auxscope should exist"

   local result
   local expect

   result="`run_mulle_env -s environment scopes --all`"
   expect="plugin
plugin-os-${MULLE_UNAME}
plugin-foo
global
os-${MULLE_UNAME}
host-${MULLE_HOSTNAME}
user-${LOGNAME}
user-foo"

   if [ "${result}" != "${expect}" ]
   then
      fail "Expected scopes:
${C_RESET}${expect}
${C_ERROR}differ from result:
${C_RESET}${result}"
   fi
   log_info "----- ALL PASSED -----"

   rmdir_safer "${directory}"
}



init()
{
   MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env libexec-dir`" || exit 1

   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1

   MULLE_ENV="${MULLE_ENV:-${PWD}/../../mulle-env}"
}



init "$@"
main "$@"

