#! /bin/sh

[ "${TRACE}" = 'YES' ] && set -x && : "$0" "$@"

###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###
MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions libexec-dir`" || exit 1
export MULLE_BASHFUNCTIONS_LIBEXEC_DIR
. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-boot.sh" || exit 1
. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1
###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###


run_mulle_env()
{
   log_fluff "####################################"
   log_fluff ${MULLE_ENV} ${MULLE_ENV_FLAGS} "$@"
   log_fluff "####################################"

   exekutor ${MULLE_ENV} ${MULLE_ENV_FLAGS} "$@"
}


main()
{
   MULLE_ENV_FLAGS="$@"

   _options_mini_main "$@" && set -x

   local directory

   r_make_tmp_directory || exit 1
   directory="${RVAL:-/tmp/exekutor}"

   cd "${directory}" || exit 1

   run_mulle_env -s init --style none/tight

   local value

   value="`run_mulle_env environment --me get FOO`"
   if [ ! -z "${value}" ]
   then
      fail "Non empty return value for get"
   fi

   if ! run_mulle_env environment --me set FOO ""
   then
      fail "Negative return value for empty set"
   fi
   if ! value="`run_mulle_env environment --me get FOO`"
   then
      fail "Negative return value for get with empty value"
   fi
   if [ ! -z "${value}" ]
   then
      fail "Non empty return value"
   fi

   log_verbose "----- #1 PASSED -----"


   if ! run_mulle_env environment --me set FOO "foo with spaces"
   then
      fail "Negative return value for empty set"
   fi
   if ! value="`run_mulle_env environment --me get FOO`"
   then
      fail "Negative return value for get with value"
   fi
   if [ "${value}" != "foo with spaces" ]
   then
      fail "Wrong return value"
   fi

   log_verbose "----- #2 PASSED -----"


   if ! run_mulle_env environment --me set FOO "bar with spaces"
   then
      fail "Negative return value for empty set"
   fi
   if ! value="`run_mulle_env environment --me get FOO`"
   then
      fail "Negative return value for get with value"
   fi
   if [ "${value}" != "bar with spaces" ]
   then
      fail "Wrong return value"
   fi

   log_verbose "----- #3 PASSED -----"


   log_info "----- ALL PASSED -----"

   rmdir_safer "${directory}"
}



init()
{
   MULLE_ENV="${MULLE_ENV:-${PWD}/../../mulle-env}"
}



init "$@"
main "$@"

